apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: view-extras
  namespace: ""
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - componentstatuses
  - services/proxy
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
# For helm
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - get
  - create
  - patch
  - delete
